### ISSUE TITLE
No such file or directory: 'MiDaS/model.pt'

### ISSUE THREAD

**Issue by hrc-coder** [vt-vl-lab/3d-photo-inpainting#103]
running on device 0
  0%|                                                                                                              | 0/1 [00:00<?, ?it/s]Current Source ==>  moon
Running depth extraction at 1599480410.2685158
initialize
device: cpu
  0%|                                                                                                              | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 54, in <module>
    config['MiDaS_model_ckpt'], MonoDepthNet, MiDaS_utils, target_w=640)
  File "C:\3d-photo-inpainting-master\MiDaS\run.py", line 29, in run_depth
    model = Net(model_path)
  File "C:\3d-photo-inpainting-master\MiDaS\monodepth_net.py", line 52, in __init__
    self.load(path)
  File "C:\3d-photo-inpainting-master\MiDaS\monodepth_net.py", line 88, in load
    parameters = torch.load(path)
  File "C:\Users\12933\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\serialization.py", line 571, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\12933\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\12933\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'MiDaS/model.pt'
这个问题我该如何解决?谢谢

**Comment by LemonATsu** [comment]
Please run the script `download.sh` for downloading pretrained weights first.
