### ISSUE TITLE
Video fails to generate, fails on line 95 torch.load

### ISSUE THREAD

**Issue by follypimpin** [vt-vl-lab/3d-photo-inpainting#113]
My machine is ubuntu 20.04, I have nvcc version 10.0 python v 3.7, when I run the command, I get this error:

Traceback (most recent call last):
  File "main.py", line 95, in <module>
    rgb_feat_weight = torch.load(config['rgb_feat_model_ckpt'],
  File "/home/develo-1/anaconda3/envs/3DP/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/develo-1/anaconda3/envs/3DP/lib/python3.8/site-packages/torch/serialization.py", line 781, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 1630865 more bytes. The file might be corrupted.

any tips would be welcome please.

**Comment by dkostenko** [comment]
the same issue

**Comment by dkostenko** [comment]
Try to download models again
