### ISSUE TITLE
对照片尺寸大小有要求吗，我传了一张249x324执行失败

### ISSUE THREAD

**Issue by handongzhe** [vt-vl-lab/3d-photo-inpainting#119]
输出信息如下：
running on device 0
  0% 0/1 [00:00<?, ?it/s]Current Source ==>  car2
Running depth extraction at 1611731040.6164544
initialize
device: cpu
start processing
  processing image/car2.jpg (1/1)
torch.Size([1, 3, 384, 320])
finished
  0% 0/1 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 72, in <module>
    vis_photos, vis_depths = sparse_bilateral_filtering(depth.copy(), image.copy(), config, num_iter=config['sparse_iter'], spdb=False)
  File "/content/3d-photo-inpainting/bilateral_filtering.py", line 31, in sparse_bilateral_filtering
    vis_image[u_over > 0] = np.array([0, 0, 0])
ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (4003,249)

**Comment by yfszzx** [comment]
I know how to repair
https://github.com/vt-vl-lab/3d-photo-inpainting/issues/176
