### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'node'

### ISSUE THREAD

**Issue by CaravanPassenger** [vt-vl-lab/3d-photo-inpainting#123]
**it happens in mesh.py, the tradeback looks like this :**

> Traceback (most recent call last):
>   File "main.py", line 112, in <module>
>     depth_feat_model)
>   File "C:\Users\guany\Desktop\3d-photo-inpainting-master\3d-photo-inpainting-master\mesh.py", line 1843, in write_ply
>     input_mesh, info_on_pix, edge_mesh, depth, aft_mark = remove_dangling(input_mesh, edge_ccs, edge_mesh, info_on_pix, image, depth, config)
>   File "C:\Users\guany\Desktop\3d-photo-inpainting-master\3d-photo-inpainting-master\mesh.py", line 764, in remove_dangling
>     mesh = refresh_node(single_edge_node, mesh.node[single_edge_node], new_node, dict(), mesh)

**and the code :**

> mesh = refresh_node(single_edge_node, mesh.node[single_edge_node], new_node, dict(), mesh)

**Looking forward to your help (**

**Comment by CaravanPassenger** [comment]
haha，actually it is such a easy question，you only need to：

> change the node to nodes
