### ISSUE TITLE
error of BoostingMonocularDepth

### ISSUE THREAD

**Issue by VrushankMPC** [vt-vl-lab/3d-photo-inpainting#155]
Getting below error while trying to do the process

(3DP) PS D:\3D\3d-photo-inpainting-master> python main.py --config argument.yml
running on device 0
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]Current Source ==>  jetbluecropped
Running depth extraction at 1649252588.5195417
'cp' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 54, in <module>
    run_boostmonodepth(sample['ref_img_fi'], config['src_folder'], config['depth_folder'])
  File "D:\3D\3d-photo-inpainting-master\boostmonodepth_utils.py", line 41, in run_boostmonodepth
    depth = imageio.imread(os.path.join(BOOST_BASE, BOOST_OUTPUTS, tgt_name))
  File "C:\Users\raipur9\MiniConda3\envs\3DP\lib\site-packages\imageio\core\functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "C:\Users\raipur9\MiniConda3\envs\3DP\lib\site-packages\imageio\core\functions.py", line 172, in get_reader
    request = Request(uri, "r" + mode, **kwargs)
  File "C:\Users\raipur9\MiniConda3\envs\3DP\lib\site-packages\imageio\core\request.py", line 124, in __init__
    self._parse_uri(uri)
  File "C:\Users\raipur9\MiniConda3\envs\3DP\lib\site-packages\imageio\core\request.py", line 260, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: 'D:\3D\3d-photo-inpainting-master\BoostingMonocularDepth\outputs\jetbluecropped.png'

**Comment by lofstone** [comment]
I have meet exactly the same issue

**Comment by 0xWhite** [comment]
https://github.com/vt-vl-lab/3d-photo-inpainting/issues/152#issuecomment-1149624759

**Comment by hsnbsrbalaban** [comment]
🚨
I solved it by changing `python` to `python3` in `boostmonodepth_utils.py - line 32`

**Comment by sumanttyagi** [comment]
@hsnbsrbalaban  still facing the same issue in linux machine

**Comment by Sylvainsbrr** [comment]
Any update ?

**Comment by unoriginalscreenname** [comment]
> 🚨 I solved it by changing `python` to `python3` in `boostmonodepth_utils.py - line 32`

This does not work.  I'm running locally on wsl2 and this repository is broken.  Stuck on exact same issue.

**Comment by unoriginalscreenname** [comment]
For what it's worth, it looks like it breaks down here in the boostmonodepth_utils.py file:

File "run.py", line 480, in estimatemidas
    prediction = midasmodel.forward(sample)

I have no idea how to debug that.  Maybe someone out there can help get it working.

**Comment by donlinglok1** [comment]
> Getting below error while trying to do the process
> 
> (3DP) PS D:\3D\3d-photo-inpainting-master> python main.py --config argument.yml running on device 0 0%| | 0/1 [00:00<?, ?it/s]Current Source ==> jetbluecropped Running depth extraction at 1649252588.5195417 'cp' is not recognized as an internal or external command, operable program or ...

i can see the log is windows system, i have a branch that can support windows system using git bash.

check here: https://github.com/vt-vl-lab/3d-photo-inpainting/pull/187

**Comment by jasonhahaha** [comment]
按照如下方法，可以运行

cd BoostingMonocularDepth
python run.py --Final --data_dir inputs/  --output_dir outputs --depthNet 0
如果报错信息为 ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found 
则参考解决方法：https://www.jianshu.com/p/fa98d384d8a1
