### ISSUE TITLE
What happened? The shell prompts that there are no nodes

### ISSUE THREAD

**Issue by jeanttz** [vt-vl-lab/3d-photo-inpainting#17]
Traceback (most recent call last):
  File "main.py", line 95, in <module>
    depth_feat_model)
  File "/home/developer/jin/3d-photo-inpainting/mesh.py", line 1841, in write_ply
    input_mesh, info_on_pix, edge_mesh, depth, aft_mark = remove_dangling(input_mesh, edge_ccs, edge_mesh, info_on_pix, image, depth, config)
  File "/home/developer/jin/3d-photo-inpainting/mesh.py", line 751, in remove_dangling
    mesh = refresh_node(single_edge_node, mesh.node[single_edge_node], new_node, dict(), mesh)
AttributeError: 'Graph' object has no attribute 'node'

**Comment by VVingerfly** [comment]
Hi, try to install networkx 2.3, see #5

**Comment by jeanttz** [comment]
yeah,&nbsp;you’re right, thank you.


发自我的iPhone


------------------ Original ------------------
