### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by rekarahuang** [vt-vl-lab/3d-photo-inpainting#202]
I have searched for related errors in the existing issues. After referring to the environment configuration method of windows version and all solutions, still cannot solve the following error

$ python main.py --config argument.yml
running on device cpu
  0%|          | 0/1 [00:00<?, ?it/s]        1 file(s) copied.
Using cache found in C:\Users\Administrator/.cache\torch\hub\facebookresearch_WSL-Images_main
device: cuda
Namespace(Final=True, R0=False, R20=False, colorize_results=False, data_dir='inputs/', depthNet=0, max_res=inf, net_receptive_field_size=None, output_dir='outputs', output_resolution=1, pix2pixsize=1024, savepatchs=0, savewholeest=0)
----------------- Options ---------------
                    Final: True                                 [default: False]
                       R0: False
                      R20: False
             aspect_ratio: 1.0
               batch_size: 1
          checkpoints_dir: ./pix2pix/checkpoints
         colorize_results: False
                crop_size: 672
                 data_dir: inputs/                              [default: None]
                 dataroot: None
             dataset_mode: depthmerge
                 depthNet: 0                                    [default: None]
                direction: AtoB
          display_winsize: 256
                    epoch: latest
                     eval: False
            generatevideo: None
                  gpu_ids: -1
                init_gain: 0.02
                init_type: normal
                 input_nc: 2
                  isTrain: False                                [default: None]
                load_iter: 0                                    [default: 0]
                load_size: 672
         max_dataset_size: 10000
                  max_res: inf
                    model: pix2pix4depth
               n_layers_D: 3
                     name: void
                      ndf: 64
                     netD: basic
                     netG: unet_1024
 net_receptive_field_size: None
                      ngf: 64
               no_dropout: False
                  no_flip: False
                     norm: none
                 num_test: 50
              num_threads: 4
               output_dir: outputs                              [default: None]
                output_nc: 1
        output_resolution: None
                    phase: test
              pix2pixsize: None
               preprocess: resize_and_crop
                savecrops: None
             savewholeest: None
           serial_batches: False
                   suffix:
                  verbose: False
----------------- End -------------------
initialize network with normal
loading the model from ./pix2pix/checkpoints/mergemodel\latest_net_G.pth
Loading weights:  midas/model.pt
Traceback (most recent call last):
  File "run.py", line 580, in <module>
    run(dataset_, option_)
  File "run.py", line 60, in run
    midasmodel.to(device)
  File "D:\Anaconda3\envs\3DP-w\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "D:\Anaconda3\envs\3DP-w\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "D:\Anaconda3\envs\3DP-w\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "D:\Anaconda3\envs\3DP-w\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "D:\Anaconda3\envs\3DP-w\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "D:\Anaconda3\envs\3DP-w\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "D:\Anaconda3\envs\3DP-w\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
  0%|          | 0/1 [00:08<?, ?it/s]
Current Source ==>  progress_5
Running depth extraction at 1683095848.6641252
BoostingMonocularDepth\inputs\*.png
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    run_boostmonodepth(sample['ref_img_fi'], config['src_folder'], config['depth_folder'])
  File "E:\Projects\3d-photo-inpainting-Windows\boostmonodepth_utils.py", line 41, in run_boostmonodepth
    depth = imageio.imread(os.path.join(BOOST_BASE, BOOST_OUTPUTS, tgt_name))
  File "D:\Anaconda3\envs\3DP-w\lib\site-packages\imageio\__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "D:\Anaconda3\envs\3DP-w\lib\site-packages\imageio\v2.py", line 348, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "D:\Anaconda3\envs\3DP-w\lib\site-packages\imageio\core\imopen.py", line 113, in imopen
    request = Request(uri, io_mode, format_hint=format_hint, extension=extension)
  File "D:\Anaconda3\envs\3DP-w\lib\site-packages\imageio\core\request.py", line 247, in __init__
    self._parse_uri(uri)
  File "D:\Anaconda3\envs\3DP-w\lib\site-packages\imageio\core\request.py", line 407, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: 'E:\Projects\3d-photo-inpainting-Windows\BoostingMonocularDepth\outputs\progress_5.png'
(3DP-w)

**Comment by takeimo** [comment]
Hi everyone,

If you are struggling to run this repository on modern environments (Python 3.10–3.13, PyTorch 2.x, NumPy 2.x) or encountering broken Conda dependencies, I have created a modernized, maintained fork called **[Tierer](https://github.com/takeimo/Tierer)**.

### What is modernized in Tierer:
* **⚡ Zero-Setup Execution via `uv`**: Fully managed by `uv` package manager with locked dependencies (`pyproject.toml` / `uv.lock`). No manual CUDA/Conda environment debugging or local C++ builds required.
* **🐍 Modern Ecosystem Compatibility**: Fully refactored and tested for **Python 3.10–3.13**, **PyTorch 2.6+**, and **NumPy 2.x** (resolving legacy NumPy/NetworkX/MoviePy/Qt6 deprecations).
* **🤖 Automatic Model Download**: Checkpoint weights are automatically fetched on the first run.
* **🖼️ Multi-Format Support**: Works out of the box with PNG (including RGBA transparency), JPG, WebP, and BMP.
* **💻 Auto-Hardware Detection**: Runs seamlessly on NVIDIA GPUs (CUDA) with automatic CPU fallback.

### Quick Start:
```bash
git clone https://github.com/takeimo/Tierer.git
cd Tierer

# Run out of the box with a single command
uv run main.py
```

*(Note regarding Google Colab: Tierer is strictly tailored for deterministic local CLI execution via `uv`. Google Colab / cloud notebooks are outside our official support scope, but local execution on Windows/Linux/Mac should work out of the box with `uv`.)*

Hope this helps anyone who wants to experiment with this amazing 3D photography technology on contemporary systems!
