### ISSUE TITLE
boolean index did not match indexed array along dimension 2; dimension is 3 but corresponding boolean dimension is 5

### ISSUE THREAD

**Issue by XXXXemberXXXX** [vt-vl-lab/3d-photo-inpainting#214]
Hi guys,when i run this project, some error shows like this,how can i fix this?

`(3DP) PS C:\Users\Demo\Desktop\3d-photo-inpainting-master> python main.py --config argument.yml
running on device 0
  0%|                                                                                                                                            | 0/1 [00:00<?, ?it/s]Current Source ==>  moon
Running depth extraction at 1719302307.669649
BoostingMonocularDepth\outputs\*.png
  0%|                                                                                                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    vis_photos, vis_depths = sparse_bilateral_filtering(depth.copy(), image.copy(), config, num_iter=config['sparse_iter'], spdb=False)
  File "C:\Users\Demo\Desktop\3d-photo-inpainting-master\bilateral_filtering.py", line 31, in sparse_bilateral_filtering
    vis_image[u_over > 0] = np.array([0, 0, 0])
IndexError: boolean index did not match indexed array along dimension 2; dimension is 3 but corresponding boolean dimension is 5
`

**Comment by 67L1** [comment]
is it work now? i meet the same problem?

**Comment by 67L1** [comment]
is it working now? i met the same problem.
