### ISSUE TITLE
No module named 'vispy'

### ISSUE THREAD

**Issue by abhinandankumarpandey** [vt-vl-lab/3d-photo-inpainting#215]
While Running  ( !python main.py --config argument.yml )

**Error**
Traceback (most recent call last):
  File "/content/3d-photo-inpainting/main.py", line 6, in <module>
    import vispy
ModuleNotFoundError: No module named 'vispy'
![Screenshot 2024-08-05 213212](https://github.com/user-attachments/assets/b432d3e8-ea04-4c7f-b868-a1f5a6e3ec91)

**Comment by phiho1609** [comment]
Weird question, but have you made sure that vispy was installed via `pip`?
If not sure, you should be able to get a list of all packages that were installed via pip with `!pip freeze --all`.
If the list is too long, you can also do `!pip freeze --all | egrep "vispy"` to only get lines that match vispy.

**Comment by amrzv** [comment]
Specified version `vispy==0.6.4` can't be installed in colab
![Image](https://github.com/user-attachments/assets/59856249-50c3-4f38-8798-5865d12a0d7b)
Removing package version unblocks 
![Image](https://github.com/user-attachments/assets/72504fa8-be45-433f-910d-cbb1674ba07d)
but rerunning `!python main.py --config argument.yml` raises another
```python
/content/3d-photo-inpainting/mesh.py:965: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  passive_background = 10 if 10 is not None else background_thickness
/content/3d-photo-inpainting/mesh.py:966: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  passive_context = 1 if 1 is not None else context_thickness
Traceback (most recent call last):
  File "/content/3d-photo-inpainting/mesh.py", line 4, in <module>
    import cynetworkx as netx
ModuleNotFoundError: No module named 'cynetworkx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/3d-photo-inpainting/main.py", line 12, in <module>
    from mesh import write_ply, read_ply, output_3d_photo
  File "/content/3d-photo-inpainting/mesh.py", line 6, in <module>
    import networkx as netx
  File "/usr/local/lib/python3.11/dist-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/usr/local/lib/python3.11/dist-packages/networkx/generators/__init__.py", line 14, in <module>
    from networkx.generators.intersection import *
  File "/usr/local/lib/python3.11/dist-packages/networkx/generators/intersection.py", line 13, in <module>
    from networkx.algorithms import bipartite
  File "/usr/local/lib/python3.11/dist-packages/networkx/algorithms/__init__.py", line 16, in <module>
    from networkx.algorithms.dag import *
  File "/usr/local/lib/python3.11/dist-packages/networkx/algorithms/dag.py", line 23, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.11/fractions.py)
```
