### ISSUE TITLE
Using CPU instead of CUDA

### ISSUE THREAD

**Issue by ModMaamari** [vt-vl-lab/3d-photo-inpainting#3]
I do not have a GPU, and want to try running the code with only a CPU.
I got the next error message:
`python main.py --config argument.yml 0%| | 0/1 [00:00<?, ?it/s]Current Source ==> moon2 initialize device: cpu start processing processing image/moon2.jpg (1/1) torch.Size([1, 3, 384, 384]) finished Start Running 3D_Photo ... Traceback (most recent call last): File "main.py", line 61, in <module> depth_edge_weight = torch.load(config['depth_edge_model_ckpt']) File "/home/user/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 529, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "/home/user/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load result = unpickler.load() File "/home/user/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 665, in persistent_load deserialized_objects[root_key] = restore_location(obj, location) File "/home/user/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 156, in default_restore_location result = fn(storage, location) File "/home/user/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 132, in _cuda_deserialize device = validate_cuda_device(location) File "/home/user/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 116, in validate_cuda_device raise RuntimeError('Attempting to deserialize object on a CUDA ' RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU. 0%| | 0/1 [00:19<?, ?it/s]`

**Comment by manish-singla** [comment]
Hi, update code from main.py as below:

`depth_edge_model = depth_edge_model.cuda(config['gpu_ids'])
`
replaced by 
```
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
depth_edge_model = depth_edge_model.to(device)

```
and

pass additional argument as below in torch.load() function calling:
```
depth_feat_weight = torch.load(config['depth_feat_model_ckpt'], map_location=torch.device('cpu'))

```

**Comment by ModMaamari** [comment]
Thanks for your fast respond, I replaced :
`depth_edge_model = depth_edge_model.cuda(config['gpu_ids'])
` by :
`device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
depth_edge_model = depth_edge_model.to(device)`

and first passed `map_location=torch.device('cpu')` to  depth_feat_weight = torch.load(config['depth_feat_model_ckpt']) 
as follows:
`depth_feat_weight = torch.load(config['depth_feat_model_ckpt'], map_location=torch.device('cpu'))`

Then I ran `python main.py --config argument.yml`, unfortunately I got the next message:

`0%|                                                     | 0/1 [00:00<?, ?it/s]Current Source ==>  moon2
initialize
device: cpu
start processing
  processing image/moon2.jpg (1/1)
torch.Size([1, 3, 384, 384])
finished
Start Running 3D_Photo ...
Traceback (most recent call last):
  File "main.py", line 61, in <module>
    depth_edge_weight = torch.load(config['depth_edge_model_ckpt'])
  File "/home/modmari/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/modmari/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "/home/modmari/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 665, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/modmari/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 156, in default_restore_location
    result = fn(storage, location)
  File "/home/modmari/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 132, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/modmari/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 116, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
  0%|                                                     | 0/1 [00:18<?, ?it/s]`

then I passed `map_location=torch.device('cpu')` to every call of torch.load()
1- `depth_edge_weight = torch.load(config['depth_edge_model_ckpt'], map_location=torch.device('cpu'))`
2- `depth_feat_weight = torch.load(config['depth_feat_model_ckpt'], map_location=torch.device('cpu'))`
3- `rgb_feat_weight = torch.load(config['rgb_feat_model_ckpt'], map_location=torch.device('cpu'))`

Then I ran `python main.py --config argument.yml` again, unfortunately I got the next message:

`  0%|                                                     | 0/1 [00:00<?, ?it/s]Current Source ==>  moon2
initialize
device: cpu
start processing
  processing image/moon2.jpg (1/1)
torch.Size([1, 3, 384, 384])
finished
Start Running 3D_Photo ...
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    depth_feat_model = depth_feat_model.cuda(config['gpu_ids'])
  File "/home/modmari/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 304, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/modmari/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/modmari/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/modmari/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/modmari/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 223, in _apply
    param_applied = fn(param)
  File "/home/modmari/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 304, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/modmari/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 196, in _lazy_init
    _check_driver()
  File "/home/modmari/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 94, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
  0%|                                                     | 0/1 [00:22<?, ?it/s]`

**Comment by LemonATsu** [comment]
We have updated the code and now you should be able to use CPU by leaving the gpu_ids in argument.yml blank.

**Comment by lonycc** [comment]
I set gpu_ids -1 in the argument.yml, then got throw the error message:

Traceback (most recent call last):
  File "main.py", line 67, in <module>
    depth_edge_weight = torch.load(config['depth_edge_model_ckpt'])
  File "/Users/work/Desktop/mixed/py/venv/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/work/Desktop/mixed/py/venv/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "/Users/work/Desktop/mixed/py/venv/lib/python3.7/site-packages/torch/serialization.py", line 665, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/Users/work/Desktop/mixed/py/venv/lib/python3.7/site-packages/torch/serialization.py", line 156, in default_restore_location
    result = fn(storage, location)
  File "/Users/work/Desktop/mixed/py/venv/lib/python3.7/site-packages/torch/serialization.py", line 132, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/Users/work/Desktop/mixed/py/venv/lib/python3.7/site-packages/torch/serialization.py", line 116, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by simfeng** [comment]
As the error message shows, in each `torch.load()`, add `map_location=torch.device('cpu')` with it, like this `depth_feat_weight = torch.load(config['depth_feat_model_ckpt'], map_location=torch.device('cpu'))`

**Comment by aquadzn** [comment]
tried `map_location=torch.device('cpu')`, `map_location='cpu'` and `map_location=lambda storage, loc: storage` but it keeps asserting `Torch not compiled with CUDA enabled 0%| | 0/1 [00:22<?, ?it/s]`

guess I'll have to try on Colab

**Comment by simfeng** [comment]
@aquadzn you should set `gpu_ids : -1` in the `argument.yml`

**Comment by lonycc** [comment]
it solved my problem, thx @simfeng

**Comment by LemonATsu** [comment]
@lonycc please make sure that you are using `networkx==2.3`. The APIs seem to be changing from version to version.

**Comment by lonycc** [comment]
@LemonATsu thx, now it works!
