### ISSUE TITLE
What should I do I get this error. thanks

### ISSUE THREAD

**Issue by alpim** [vt-vl-lab/3d-photo-inpainting#34]
^[[C(base) alpi@alpi-VirtualBox:~/Downloads/3d-photo-inpainting-master$ python mpy --config argument.yml
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from mesh import write_ply, read_ply, output_3d_photo
  File "/home/alpi/Downloads/3d-photo-inpainting-master/mesh.py", line 17, in <module>
    import torch
  File "/home/alpi/anaconda3/lib/python3.7/site-packages/torch/__init__.py", line 181, in <module>
    from .serialization import save, load
  File "/home/alpi/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 448, in <module>
    def load(f, map_location=none, pickle_module=pickle, **pickle_load_args):
NameError: name 'none' is not defined
(base) alpi@alpi-VirtualBox:~/Downloads/3d-photo-inpainting-master$

**Comment by LemonATsu** [comment]
Hi, can you provide more information about your environment (e.g., os spec, how you run it, etc)

**Comment by alpim** [comment]
Hi,
the problem i am having now

(base) alpi@alpi-VirtualBox:~/Downloads/3d-photo-inpainting-master$ python main.py --config argument.yml
  0%|                                                                                               | 0/1 [00:00<?, ?it/s]Current Source ==>  moon
initialize
device: cpu
  0%|                                                                                               | 0/1 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    config['MiDaS_model_ckpt'], MonoDepthNet, MiDaS_utils, target_w=640)
  File "/home/alpi/Downloads/3d-photo-inpainting-master/MiDaS/run.py", line 29, in run_depth
    model = Net(model_path)
  File "/home/alpi/Downloads/3d-photo-inpainting-master/MiDaS/monodepth_net.py", line 52, in __init__
    self.load(path)
  File "/home/alpi/Downloads/3d-photo-inpainting-master/MiDaS/monodepth_net.py", line 88, in load
    parameters = torch.load(path)
  File "/home/alpi/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/alpi/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/alpi/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'MiDaS/model.pt'
(base) alpi@alpi-VirtualBox:~/Downloads/3d-photo-inpainting-master$

**Comment by alpim** [comment]
I do everything exactly

**Comment by LemonATsu** [comment]
@alpim Please follow the instruction to run `download.sh` to download the pre-train model weights. Also, please make sure that your virtual env is correctly set up with the required packages.
