### ISSUE TITLE
I don't know why it's not working.

### ISSUE THREAD

**Issue by gw3285** [vt-vl-lab/3d-photo-inpainting#35]
I don' know why it's not working.
I would appreciate it if anyone who knows the reason would answer.

0%|                                                                                                                                | 0/2 [00:00<?, ?it/s]Current Source ==>  moon
initialize
device: cpu
start processing
  processing image/moon.jpg (1/1)
torch.Size([1, 3, 384, 320])
finished
Start Running 3D_Photo ...
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    map_location=torch.device(device))
  File "/home/nim924/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/nim924/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "/home/nim924/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 665, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/nim924/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 740, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/home/nim924/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 156, in default_restore_location
    result = fn(storage, location)
  File "/home/nim924/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 132, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/nim924/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 116, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
  0%|                                                                                                                                | 0/2 [00:10<?, ?it/s]

**Comment by LemonATsu** [comment]
It seems like you don't have GPU on your machine. Try setting `gpu_ids=-1` in your `argument.yml`. You can also play with the colab we provided (which can utilize free online GPU resource)

**Comment by gw3285** [comment]
gpu_ids = -1 attempted, but the following error occurred:

 0%|                                                                                                                          | 0/2 [00:00<?, ?it/s]Current Source ==>  moon
initialize
device: cpu
start processing
  processing image/moon.jpg (1/1)
torch.Size([1, 3, 384, 384])
finished
Start Running 3D_Photo ...
Writing mesh file mesh/moon.ply ...
53.13010235415598
WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-nim924'
WARNING: QXcbConnection: Could not connect to display 
WARNING: Could not connect to any X display.

I would appreciate your reply.

**Comment by LemonATsu** [comment]
Try using the `offscreen_rendering` to `True` in your `argument.yml`
