### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by fengxinxin** [vt-vl-lab/3d-photo-inpainting#44]
`(3DP) bogon:3d-photo-inpaint$ python main.py --config argument.yml
  0%|                                                                                                                                                                                 | 0/1 [00:00<?, ?it/s]Current Source ==>  moon
initialize
device: cpu
start processing
  processing image/moon.jpg (1/1)
torch.Size([1, 3, 384, 384])
finished
Start Running 3D_Photo ...
  0%|                                                                                                                                                                                 | 0/1 [02:38<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    depth_feat_model)
  File "/Users/iOLO/dev/Python/3d-photo-inpainting/mesh.py", line 1864, in write_ply
    depth_edge_model, depth_feat_model, rgb_model, config, direc="up")
  File "/Users/iOLO/dev/Python/3d-photo-inpainting/mesh_tools.py", line 193, in extrapolate
    t_edge = torch.FloatTensor(edge).to(device)[None, None, ...]
  File "/Users/iOLO/opt/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/cuda/__init__.py", line 196, in _lazy_init
    _check_driver()
  File "/Users/iOLO/opt/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/cuda/__init__.py", line 94, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled`

**Comment by fengxinxin** [comment]
done

**Comment by unknownArtist** [comment]
Any update regarding this issue.. 
I am on mac.. and facing same issue when running command  python main.py --config argument.yml

**Comment by unknownArtist** [comment]
@fengxinxin i overcome this issue after setting value **gpu_ids: -1** in  argument.yml
