### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'node'

### ISSUE THREAD

**Issue by VVingerfly** [vt-vl-lab/3d-photo-inpainting#5]
Thanks for the amazing and awesome work.

I tried to run the code on my Macbook which does not have a CUDA GPU. But it fails with the following message:

```
python main.py --config argument.yml
  0%|                                                                                                                         | 0/1 [00:00<?, ?it/s]Current Source ==>  moon
initialize
device: cpu
start processing
  processing image/moon.jpg (1/1)
torch.Size([1, 3, 384, 384])
finished
Start Running 3D_Photo ...
  0%|                                                                                                                         | 0/1 [00:50<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 95, in <module>
    depth_feat_model)
  File "3d-photo-inpainting/mesh.py", line 1841, in write_ply
    input_mesh, info_on_pix, edge_mesh, depth, aft_mark = remove_dangling(input_mesh, edge_ccs, edge_mesh, info_on_pix, image, depth, config)
  File "3d-photo-inpainting/mesh.py", line 751, in remove_dangling
    mesh = refresh_node(single_edge_node, mesh.node[single_edge_node], new_node, dict(), mesh)
AttributeError: 'Graph' object has no attribute 'node'
```

How can I resolve this problem? Thanks a lot!

B. R.

**Comment by ShihMengLi** [comment]
Could you show the version of package `networkx` ?
This should be `networkx==2.3`. 
The attribute 'node' has been deprecated since version 2.4.

**Comment by VVingerfly** [comment]
Thanks for your quick reply!
I reinstalled `networkx` 2.3, and it works now!

Thanks a lot!
