### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CGVA3** [vt-vl-lab/3d-photo-inpainting#70]
Start Running 3D_Photo ...
Loading edge model at 1593325872.7909162
  0%|                                                                                                                                                          | 0/1 [01:17<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    map_location=torch.device(device))
  File "/Users/---/anaconda3/envs/3DPhotoCreator/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/Users/---//anaconda3/envs/3DPhotoCreator/lib/python3.7/site-packages/torch/serialization.py", line 613, in _load
    result = unpickler.load()
  File "/Users/---//anaconda3/envs/3DPhotoCreator/lib/python3.7/site-packages/torch/serialization.py", line 576, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/Users/---//anaconda3/envs/3DPhotoCreator/lib/python3.7/site-packages/torch/serialization.py", line 446, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/Users/---//anaconda3/envs/3DPhotoCreator/lib/python3.7/site-packages/torch/serialization.py", line 155, in default_restore_location
    result = fn(storage, location)
  File "/Users/---//anaconda3/envs/3DPhotoCreator/lib/python3.7/site-packages/torch/serialization.py", line 131, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/Users/---//anaconda3/envs/3DPhotoCreator/lib/python3.7/site-packages/torch/serialization.py", line 115, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by freeman5** [comment]
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

Its already say in documentation or other issue you just have you delete the 0 at gpu argument in argument.yml
