### ISSUE TITLE
Problem with PyQt5

### ISSUE THREAD

**Issue by bibhas2** [vt-vl-lab/3d-photo-inpainting#83]
I am running in a docker container in macOS. I think the container is missing OpenGL. How do I fix that?

``main.py`` is failing after a long time with this message.

```
WARNING: Could not load OpenGL library.
running on device cpu
  0%|                                                                                                       | 0/1 [00:00<?, ?it/s]Current Source ==>  moon
Running depth extraction at 1595437846.1242821
initialize
device: cpu
start processing
  processing image/moon.jpg (1/1)
torch.Size([1, 3, 384, 384])
finished
Start Running 3D_Photo ...
Loading edge model at 1595437869.7599049
Loading depth model at 1595437869.9819047
Loading rgb model at 1595437871.283845
Writing depth ply (and basically doing everything) at 1595437872.7684999
Writing mesh file mesh/moon.ply ...
Making video at 1595438313.7236035
fov: 53.13010235415598
WARNING: Although PyQt5 is already imported, the PyQt5 backend could not
be used ("libGL.so.1: cannot open shared object file: No such file or directory"). 
Note that running multiple GUI toolkits simultaneously can cause side effects.
  0%|                                                                                                       | 0/1 [07:52<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 137, in <module>
    mean_loc_depth=mean_loc_depth)
  File "/3d-photo-inpainting/mesh.py", line 2203, in output_3d_photo
    proj='perspective')
  File "/3d-photo-inpainting/mesh.py", line 2134, in __init__
    self.canvas = scene.SceneCanvas(bgcolor=bgcolor, size=(canvas_size*factor, canvas_size*factor))
  File "/opt/conda/envs/3DP/lib/python3.7/site-packages/vispy/scene/canvas.py", line 137, in __init__
    always_on_top, px_scale)
  File "/opt/conda/envs/3DP/lib/python3.7/site-packages/vispy/app/canvas.py", line 169, in __init__
    self._app = use_app(call_reuse=False)
  File "/opt/conda/envs/3DP/lib/python3.7/site-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/opt/conda/envs/3DP/lib/python3.7/site-packages/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "/opt/conda/envs/3DP/lib/python3.7/site-packages/vispy/app/application.py", line 256, in _use
    'PyQt' % [b[0] for b in CORE_BACKENDS])
RuntimeError: Could not import any of the backends. You need to install any of ['PyQt4', 'PyQt5', 'PySide', 'PySide2', 'Pyglet', 'Glfw', 'SDL2', 'wx', 'EGL', 'osmesa']. We recommend PyQt
```

**Comment by liviclee** [comment]
I meet the same issue.

**Comment by liviclee** [comment]
Update:
I refer to this page: https://gist.github.com/ujjwal96/1dcd57542bdaf3c9d1b0dd526ccd44ff and solve the problem.
## Installation

```
pip3 install --user pyqt5  
sudo apt-get install python3-pyqt5  
sudo apt-get install pyqt5-dev-tools
sudo apt-get install qttools5-dev-tools
```
____
## Configuring to run from terminal

`$ qtchooser -run-tool=designer -qt=5`
