### ISSUE TITLE
Using CPU Instead of cuda

### ISSUE THREAD

**Issue by Steinful32** [vt-vl-lab/3d-photo-inpainting#86]
Tried to use CPU Instead of cuda by replacing the gpu ids to -1 and then going into argument.yml and replacing "device" with "cpu"

**Comment by LemonATsu** [comment]
You don't have to replace `device` with `cpu`. Setting the device flag to -1 should be sufficient.

**Comment by Anonymous7code** [comment]
Except that give a try to Colab/Asure it will provide GPU rendering without any high computational work and can also be run locally in the computer

**Comment by doogyhatts** [comment]
I was trying CPU mode but I got this error for the BoostingMonocularDepth:

`Traceback (most recent call last):
  File "C:\tools\3d-photo-inpainting\BoostingMonocularDepth\run.py", line 580, in <module>
    run(dataset_, option_)
  File "C:\tools\3d-photo-inpainting\BoostingMonocularDepth\run.py", line 48, in run
    opt = TestOptions().parse()
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\3d-photo-inpainting\BoostingMonocularDepth\pix2pix\options\base_options.py", line 152, in parse
    torch.cuda.set_device(opt.gpu_ids[0])
  File "C:\ProgramData\anaconda3\Lib\site-packages\torch\cuda\__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'`

**Comment by o0ocuchuoio0o** [comment]
> I was trying CPU mode but I got this error for the BoostingMonocularDepth:
> 
> `Traceback (most recent call last): File "C:\tools\3d-photo-inpainting\BoostingMonocularDepth\run.py", line 580, in <module> run(dataset_, option_) File "C:\tools\3d-photo-inpainting\BoostingMonocularDepth\run.py", line 48, in run opt = TestOptions().parse() ^^^^^^^^^^^^^^^^^^^^^ File "C:\tools\3d-photo-inpainting\BoostingMonocularDepth\pix2pix\options\base_options.py", line 152, in parse torch.cuda.set_device(opt.gpu_ids[0]) File "C:\ProgramData\anaconda3\Lib\site-packages\torch\cuda\__init__.py", line 350, in set_device torch._C._cuda_setDevice(device) ^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'`

I also have this error but I don't know how to fix it. Have you solved it yet?

**Comment by doogyhatts** [comment]
> I also have this error but I don't know how to fix it. Have you solved it yet?

I haven't been using it since I got GPU mode to work.

**Comment by o0ocuchuoio0o** [comment]
> > I also have this error but I don't know how to fix it. Have you solved it yet?
> 
> I haven't been using it since I got GPU mode to work.

thank you i fix complete
